### ISSUE TITLE
Updating an existing dylint lint

### ISSUE THREAD

**Issue by newcomertv** [trailofbits/dylint#1264]
Hey,

The project is awesome and really helped me out in a pinch when I needed to write a quick and dirty lint.

After abandoning my quick lint and coming back to give it some much needed love I came across this issue:

Based on the documentation I wasn't able how to figure out how to update an existing dylint lint.
My steps to reproduce are probably pretty vague since I originally wrote the lint a couple months ago..

Steps I did:
- Create a new lint using dylint new ..
- Edit
- Use a bunch
- Update toolchains
- Use a bunch
- Edit
- cargo build
- -> lint doesn't update, uses old description and way of operating (the old .so)

- run cargo clean
- library not found
- cargo build
- library not found
- cargo dylint --lib-path path/to/release/lint.so
- invalid filename, does not respect the format

At this point I'm expecting there to be a magic trick how to re-register a dylint lint without needing to run cargo dylint new

NOTE: I have a rust-toolchain.toml

Link to project: https://github.com/newcomertv/parameter-prefix-dylint-rs

**Comment by smoelius** [comment]
Hi, @newcomertv. Thanks for your kind words, and thanks for providing the link to the repo.

The "magic trick" is this:
```sh
cargo dylint upgrade .
```
This will update your project's `rust-toolchain` file to a newer nightly channel, and update the `clippy_utils` dependency in the Cargo.toml file.

I tried this on you project and ran into an issue with `cx.opt_span_lint`. I think you're project may have been bitten by: https://github.com/rust-lang/rust/pull/125410

I removed this line and everything seemed to build: https://github.com/newcomertv/parameter-prefix-dylint-rs/blob/aa41c9481cbd3d01fd2dc877eec6a1f7f094b650/src/lib.rs#L119

I would need to study that PR more to know if this is the "right" fix, though.

Please let me know if I have misunderstood what you were asking about.

**Comment by smoelius** [comment]
> After running cargo dylint upgrade it updated the toolchain to the nightly from the 25th of July. (4 days ago)
I'm guessing that was my latest rust nightly already installed.

This is actually based on what Clippy uses: https://github.com/rust-lang/rust-clippy/blob/f7db8952e611e359ce3fb04c85d2ffb92036a55c/rust-toolchain#L2

Since `clippy_utils` uses Rust's internal APIs, Dylint has to upgrade the `clippy_utils` version and Rust toolchain channel in tandem (i.e., to make sure they stay in sync).

> My understanding is its supposed to work with the specific date as well. With dylint being supposed to take whatever nightly my lint specifies.

At a high level, that is correct. But how was your lint specifying the date? In other words, what date were you expecting Dylint to find that it was not?

The way Dylint normally finds the date is from the filename (as I think you figured out).

Also, I noticed that the repo does not include a `.cargo/config.toml` file. You might consider adding one like this: https://github.com/trailofbits/dylint/blob/08992ae72df0e2098673d3dc25b4d44df21dc353/examples/general/.cargo/config.toml#L4-L5
That will cause a file with the toolchain date to be generated automatically.
