### ISSUE TITLE
Lint configuration settings

### ISSUE THREAD

**Issue by shepmaster** [trailofbits/dylint#482]
Is there some way of having configuration for a lint? For example, I'd like to have a list of methods that should be ignored by my lint.

As an aside, is there a better way of asking question than opening issues? Something like GitHub discussions / a forum / Discord server / etc.?

**Comment by smoelius** [comment]
Hi, @shepmaster.

> Is there some way of having configuration for a lint? For example, I'd like to have a list of methods that should be ignored by my lint.

Short answer, no.

But I too [have needed functionality like this](https://github.com/trailofbits/dylint/blob/7e58101f0d2b03f0e93f934fecca1dfd14672632/examples/general/non_local_effect_before_error_return/src/visit_error_paths.rs#L319-L323). So maybe it's time to implement it.

I was trying to imagine what an interface could look like, and here is what I came up with:
```rust
    type TomlResult<T> = Result<T, <toml::Value as std::str::FromStr>::Err>;

    fn config_toml(sess: &Session, name: &str) -> TomlResult<Option<toml::Value>>;

    fn config<T: serde::de::DeserializeOwned>(
        sess: &Session,
        name: &str,
    ) -> TomlResult<Option<T>>;

    fn config_or_default<T: Default + serde::de::DeserializeOwned>(
        sess: &Session,
        name: &str,
    ) -> TomlResult<T>;
```
The idea would be that one puts a `dylint.toml` file in the root directory of their workspace, with entries like:
```toml
[bad_practice]
setting = 0
```
Then, the `bad_practice` lint would do something like this:
```rust
    #[derive(Debug, Default, serde::Deserialize)]
    struct BadPracticeConfig {
        setting: u64,
    }

    let config = dylint_linting::config_or_default::<BadPracticeConfig>(cx.sess(), env!("CARGO_PKG_NAME"))
        .unwrap();
```
Does this sound like it could work for you?

(It would probably take me only a few days to implement.)

> As an aside, is there a better way of asking question than opening issues? Something like GitHub discussions / a forum / Discord server / etc.?

The repo doesn't get that much traffic. So I think opening issues for questions is perfectly fine.

**Comment by shepmaster** [comment]
I believe something like that should work, yeah! in my case, I'd have something like

```toml
[expensive_function_call_in_context]
allowed = ["path::to::my::Type::cheap_method", "and::another::function"]
```

I'm a little unclear on how/where the lint would store this config, which I suppose is another question. When I use `declare_late_lint!`, I get a struct for my lint, but is it possible to have some state in there? Specifically, I'm thinking about anything that might be expensive to compute and that could be used across lints. This config is one such example, and I was also thinking about how I would store some interned symbols.

I lightly poked into `declare_late_lint!` but didn't see anything obvious to allow this.

**Comment by smoelius** [comment]
> When I use `declare_late_lint!`, I get a struct for my lint, but is it possible to have some state in there?

Using `impl_late_lint!` instead of `declare_late_lint!` allows you to declare the struct yourself, so you can put fields in there. Here is an example (also note that `impl_late_lint!` takes one more argument): https://github.com/trailofbits/dylint/blob/c36f2797522e9a5fb90490983481ff5a9a2d4679/examples/restriction/unnecessary_conversion_for_trait/src/lib.rs#L50-L81

> I'm a little unclear on how/where the lint would store this config, which I suppose is another question.

I think this is the right question to ask.

So, first, I think `config_or_default`, etc. could cache the `dylint.toml` (parsed as a `toml::Table`) in the background. So, for example, there would be only one read of the file.

Then, a lint could do (at least) one of three things:
1. (Easiest/least efficient) Call `config_or_default` each time the config is needed. This would repeat Serde deserialization each time the config is needed (not ideal), but would not reread the file (as mentioned above).
2. (Medium) Use `impl_late_lint!` and store the config in a [`OnceCell`](https://docs.rs/once_cell/latest/once_cell/sync/struct.OnceCell.html), e.g., something like:
    ```rust
    struct BadPractice {
        config: OnceCell<BadPracticeConfig>,
    }
    ...
        fn check_expr(&mut self, cx: &LateContext<'tcx>, expr: &'tcx Expr<'tcx>) {
            ...
            let setting = self.config.get_or_init(|| {
                dylint_linting::config_or_default::<BadPracticeConfig>(cx.sess(), env!("CARGO_PKG_NAME")).unwrap()
            }).setting;
            ...
        }
    ```
    This should be reasonably efficient (e.g., just one Serde deserializtion), but is less ergonomic, e.g., because of the need to use `get_or_init`.
3. (Hardest/most efficient) Not use `declare_late_lint!`/`impl_late_lint!` and implement the `register_lints` function manually ([example](https://github.com/trailofbits/dylint/blob/c36f2797522e9a5fb90490983481ff5a9a2d4679/examples/general/non_thread_safe_call_in_test/src/lib.rs#L18-L31)).

The challenge is getting hold of the [`Session`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_session/struct.Session.html) object, which is needed to determine the root of the workspace. The `Session` is available in `register_lints`, for example. But I cannot (at the moment) think of a good/robust/portable way of accessing the `Session` from within a macro like `declare_late_lint!`/`impl_late_lint!`. This deserves more thought, though.

**Comment by shepmaster** [comment]
I think that options 1 and 2 are pretty reasonable. In my WIP lint, I'm assuming that I'll be able to access _something_ in my constructor and then go from there. This avoids the need to have a check inside the lint implementation:

```rust
struct SnafuContextFunCall {
    context_like: Vec<Vec<Symbol>>,
    allowed_calls: Vec<Vec<Symbol>>,
}

impl Default for SnafuContextFunCall {
    fn default() -> Self {
        let context_like = intern_paths(CONTEXT_LIKE_METHODS);
        let mut allowed_calls = intern_paths(ALLOWED_METHODS);

        // These string literals would actually come from the config:
        let allowed_by_user = intern_paths(&[&["iox_query", "QueryChunk", "id"]]);
        allowed_calls.extend(allowed_by_user);

        Self {
            context_like,
            allowed_calls,
        }
    }
}
```

> The challenge is getting hold of the [`Session`](https://doc.rust-lang.org/nightly/nightly-rustc/rustc_session/struct.Session.html) object,

I'm talking completely out of my depth here, but it looks like a lint [can get a `TyCtxt`](https://github.com/trailofbits/dylint/blob/c36f2797522e9a5fb90490983481ff5a9a2d4679/utils/linting/src/lib.rs#L57) and then get the `Session` via [`sess`](https://doc.rust-lang.org/beta/nightly-rustc/rustc_middle/ty/struct.TyCtxt.html#method.sess). Then that can be passed to the lint constructor expression.

**Comment by shepmaster** [comment]
Another thing to consider is cache invalidation — it'd be ideal if updating the configuration caused the lints to be re-run. Right now, I have to `cargo clean` my target crates whenever I make changes to the lint and I'd expect that changes to the config will have the same problem.

**Comment by smoelius** [comment]
> I'm talking completely out of my depth here, but it looks like a lint [can get a `TyCtxt`](https://github.com/trailofbits/dylint/blob/c36f2797522e9a5fb90490983481ff5a9a2d4679/utils/linting/src/lib.rs#L57) and then get the `Session` via [`sess`](https://doc.rust-lang.org/beta/nightly-rustc/rustc_middle/ty/struct.TyCtxt.html#method.sess). Then that can be passed to the lint constructor expression.

You're right. The point I was trying to make was that the `Session` object must be available when the configuration file is read. So either the read has to happen in a context where the `Session` is already available (e.g., in `register_lints`), or the caller/lint has to make the `Session` available, e.g., by obtaining it in the manner you described.

In any case, I think I found a better way to manage access to the `Session`. Long story short: the `register_lints` function that is automatically generated by `impl_late_lint!`, etc. will perform the read.

There is a prototype implementation in the `config` branch of this repository. You should be able to test it by referring to `dylint_linting` as follows in your `Cargo.toml`:
```
dylint_linting = { git = "https://github.com/trailofbits/dylint", branch = "config" }
```

Because I am managing access to the `Session` differently, the interface is slightly different than I described in https://github.com/trailofbits/dylint/issues/482#issuecomment-1311615210.

I expect most uses of the new interface to look something like this (note the use of `dylint_linting::config_or_default`): https://github.com/trailofbits/dylint/blob/de94052e5f736a048efc567b2f7b8f0fd0020135/examples/restriction/suboptimal_pattern/src/lib.rs#L67-L90

Please don't feel obligated to test this, though.

> Another thing to consider is cache invalidation — it'd be ideal if updating the configuration caused the lints to be re-run.

Thanks! If I did things right, changing the `dylint.toml` file should trigger a recheck.

> Right now, I have to `cargo clean` my target crates whenever I make changes to the lint...

Yeah, I've been burned by this too. I need to find a better solution for this.

**Comment by shepmaster** [comment]
> Please don't feel obligated to test this, though.

Nice try! I did test and it does appear to work for [my case](https://github.com/shepmaster/snafu-lints/tree/main/perf/snafu_context_fun_call) ❤️ . 

A few random suggestions (let me know if you'd rather I file separate issues for these):

- Add a section to the docs for "configuration". [my example](https://github.com/shepmaster/snafu-lints/tree/7c9a6ea3eca598aa49edf65e8d7effd8d5cee41c/perf/snafu_context_fun_call#configuration)
- Use Markdown headings instead of bold for the subsections — note how I was able to link to it above 😉 
- Reduce duplication of the documentation by using `#[doc = include_str("path/to/readme")]` [my example](https://github.com/shepmaster/snafu-lints/blob/7c9a6ea3eca598aa49edf65e8d7effd8d5cee41c/perf/snafu_context_fun_call/src/lib.rs#L35)

**Comment by smoelius** [comment]
> * Add a section to the docs for "configuration". [my example](https://github.com/shepmaster/snafu-lints/tree/7c9a6ea3eca598aa49edf65e8d7effd8d5cee41c/perf/snafu_context_fun_call#configuration)

💯 That will be my next commit.

> * Use Markdown headings instead of bold for the subsections — note how I was able to link to it above 😉

I think we will want to do this en masse. So I will probably handle this with a separate PR.

> * Reduce duplication of the documentation by using `#[doc = include_str("path/to/readme")]` [my example](https://github.com/shepmaster/snafu-lints/blob/7c9a6ea3eca598aa49edf65e8d7effd8d5cee41c/perf/snafu_context_fun_call/src/lib.rs#L35)

This is a neat trick, and one I did not know was possible. The only reason why I hesitate is that I like being able to read a lint's documentation alongside its code without having having to switch files. I will continue to think about this though.

Thank you very much for the suggestions.
